### ISSUE TITLE
CGI関連のモジュールをdockerディレクトリの外に出す。

### ISSUE THREAD

**Issue by katataku** [katataku/webserv#11]
### Description

今はとりあえずコンテナ起動させられる状態にしただけで、一旦dockerディレクトリ内に、色々残ってます。

**Comment by katataku** [comment]
```
src/CGI
```
というディレクトリ作ると
- python製のCGIプログラム
- webserv側でCGI関連の処理を担当するモジュール
のどっちかわからなくなるなって思いました。

ルート直下にCGIってディレクトリ切っていいですか？

**Comment by Yamada-Ika** [comment]
確かにそうだと思います！
python製のCGIプログラムは動作チェックなどのテスト時に使うもので、テストデータはまとめておきたい感じはあります。プロジェクトルート直下で、よくあるwebサーバーのディレクトリ構造っぽく下のようにするのはどうですか？

```
% tree testdata 
testdata
└── www
    ├── cgi-bin
    │   └── cgi_script
    └── html
        └── index.html
```

**Comment by hayashi-ay** [comment]
いかさんの案良さそう。publicディレクトリを切ってそこにerror pageやfaviconなどと一緒にCGIプログラムを置いてあげるのが良さそう。

**Comment by hayashi-ay** [comment]
publicディレクトリ以下に静的なコンテンツを置くことが多いです。↓下はNextの例
https://github.com/hayashi-ay/haya3/tree/main/public
