### ISSUE TITLE
cgiじゃないpost/deleteの挙動整理。spec.mdに明記する

### ISSUE THREAD

**Issue by Yamada-Ika** [katataku/webserv#124]

**Comment by Yamada-Ika** [comment]
POSTを実装しないとこの要件は満たさないかなーって感じです

> Clients must be able to upload files.

POSTとDELETEはCGIプログラムがないと機能しませんが、今回はウェブサーバーを実装する課題であり、POSTとDELETEができるCGIプログラムの実装は課題の範疇ではないです。
従って、以下の文章からGET、POST、DELETEメソッドを処理でき、POSTではファイルをアップロードできるウェブサーバーを実装する必要がある、と読み取れるかなーって思います

> Clients must be able to upload files.
> You need at least GET, POST, and DELETE methods.

**Comment by katataku** [comment]
テスターもPOST/DELETEを期待しているよう。

**Comment by katataku** [comment]
対応する！
