### ISSUE TITLE
chunked requestのbody終了判定

### ISSUE THREAD

**Issue by katataku** [katataku/webserv#165]
### Description

[RFC](https://triple-underscore.github.io/RFC7230-ja.html#chunked.encoding)ではchunked requestのbody終了判定は以下のように規定されている。
```
チャンク化転送符号法が完了するのは、
［ chunk-sizeゼロのチャンク — 場合によってはトレイラ節後続する — が受信され，最後に 空行により終了された ］
ときである。
```
つまり、bodyの最後に`0<CR><LF><CR><LF>`が来た時である。

現状の実装では`0<CR><LF>`のパターンで400エラーを返せていない。（chunk-sizeゼロのチャンク の受信が終了した時点で処理が終了しているため）

**Comment by katataku** [comment]
@hayashi-ay いまRFC見直してて気になったんですが、これって認識あってますかね？

**Comment by hayashi-ay** [comment]
@katataku なるほど〜。試してみたら400は返さないでCRLFが来るのを待つ挙動でした。

**Comment by katataku** [comment]
> @katataku なるほど〜。試してみたら400は返さないでCRLFが来るのを待つ挙動でした。

試してくださってあざます。待つのか！たしかに

**Comment by hayashi-ay** [comment]
あと細かいことを言うとトレーラーというのが続けるので0CRLFとCRLFの間に何かしら来ても大丈夫そうでした。
