### ISSUE TITLE
ClangFormatをGithub Actionsで確認するようにする&修正する

### ISSUE THREAD

**Issue by hayashi-ay** [katataku/webserv#64]
### Description

ClangFormatでフォーマットされていないソースコードがコミットされてしまっている。

**Comment by katataku** [comment]
google testとは別にstd=c++98の確認のために、コンパイルが成功するかも確認しても良いかも

**Comment by hayashi-ay** [comment]
たしかに。

**Comment by hayashi-ay** [comment]
`-Wall -Wextra -Werror`でコンパイルできないのも検知できてないですね。
